name: CatchBall
main: com.github.nutt1101.CatchBall
author: NUTT1101
description: "§bA plugin that make entity to be catchable.\n§dContact Me: https://discord.link/nuttPluginClub"
version: "1.1.6"
api-version: 1.19
load: STARTUP
softdepend: [Residence, MythicMobs, GriefPrevention]
permissions:
  catchball.op:
    default: op
  catchball.use:
    default: true
commands:
  ctb:
    description: "Command Help : /ctb"
    